### ISSUE TITLE
Str SEQ instead of int TID in trade entry in Websocket API trades channel

### ISSUE THREAD

**Issue by orme** [bitfinexcom/api_docs#13]
I've noticed that BFX replaced int TID field with str SEQ field in Websocket trades channel without changing API version. It is now really hard to map trades from WS API to trades from REST API (for filling gaps for example). Is it possible to get trades with SEQ via REST API or may be there's some other mapping method? BTW BFX provides timestamp in seconds (not millis) and it was handy to sort trades by tid. I think that this update can break some client's logic.

**Comment by prdn** [comment]
Hi @orme . The mapping between Websocket SEQ and real trade ids is offered by the private stream.
This means that you can do that kind of mapping only for your trades.
This allow us to send the trade messages as soon as they are generated by the trading engine.

**Comment by prdn** [comment]
We are discussing to send an update message to remap SEQ with tradeid (from rest) as we do in the private channel.

**Comment by prdn** [comment]
It will go live today
