### ISSUE TITLE
Raw order book isn't working as documented

### ISSUE THREAD

**Issue by joshmyzie2** [bitfinexcom/api_docs#14]
```
{"event":"subscribe","channel":"book","pair":"BTCUSD","prec":"R0"}
{"channel":"book","pair":"BTCUSD","prec":"R0","event":"error","msg":"precision not found","code":10300}
```

**Comment by prdn** [comment]
Hello

Sorry for the delay. 
We have the fix ready to be pushed but we had to delay the update till Monday. 

The update will fix the raw book and some latency improvements.

**Comment by slacknation** [comment]
prec should be P0 not R0?

**Comment by prdn** [comment]
R0 is the precision value that indicates the raw book.
