### ISSUE TITLE
websocket's 'account info' navigates to REST's 'account info'

### ISSUE THREAD

**Issue by slacknation** [bitfinexcom/api_docs#18]
clicking on 'account info' under websocket>authenticated channels navigates the page to the REST's 'account info' instead. think it is a bug with slate not assigning a different bookmark name to duplicate headings with spaces. hope that the 'account info' could be change to not contain space or a different name

**Comment by prdn** [comment]
Fixed in upcoming update.

**Comment by slacknation** [comment]
issue solved but now clicking REST's 'account info' navigates to websocket's 'account info'

**Comment by joshuarossi** [comment]
it doesn't actually navigate their, but the table of contents on the right moves to the websocket version, i changed the websocket version to "Account Information" while the REST one is "Account Info"
