### ISSUE TITLE
Wrong info about ws heartbeating

### ISSUE THREAD

**Issue by jussirantala** [bitfinexcom/api_docs#20]
The documentation says "If there is no new message in the channel for 5 seconds, Websocket server will send you an heartbeat message in this format."

But it sends a hearbeat every second. Thats good though IMO.

http://docs.bitfinex.com/#heartbeating

**Comment by prdn** [comment]
Thanks for reporting this.
You're right.
@joshuarossi can you address the change in our docs?

Thanks

**Comment by prdn** [comment]
Done
