### ISSUE TITLE
Returned price_precision is not correct

### ISSUE THREAD

**Issue by scrawl** [bitfinexcom/api_docs#36]
symbol_details returns a price_precision of 5 for all pairs. 
https://api.bitfinex.com/v1/symbols_details

But the actual precision, determined experimentally by entering orders, appears to be different, e.g.:
btcusd - 2
ethbtc - 6
ethusd - 3

**Comment by prdn** [comment]
@scrawl 5 is the number of sig figures, not the number of decimals

**Comment by scrawl** [comment]
d'oh, you are correct! My bad for not reading the docs carefully.
