### ISSUE TITLE
hidden order returned as 0 instead of 1 in last field of websocket order (on,ou,oc) messages

### ISSUE THREAD

**Issue by slacknation** [bitfinexcom/api_docs#5]

**Comment by joshuarossi** [comment]
this wasn't actually specified in the docs, but I will add the field into the table and then make sure that 0 means "NOT HIDDEN" and 1 means "HIDDEN" (expected behavior)

**Comment by slacknation** [comment]
it wasn't in the field but was in the javascript code on the right. anyway I meant that it returned 0 for hidden and not hidden orders.

**Comment by joshuarossi** [comment]
ah, thanks.

**Comment by joshuarossi** [comment]
ah, are you talking about the REST calls?

**Comment by joshuarossi** [comment]
ok, can you tell me which part of the docs? 

In the rest portion, it uses the words "false" and "true", in the web sockets, it refers to that field as 
"<ORD_HIDDEN>"

so, I am just trying to find the area where the docs refer to any numeric value specifically in relation to order hidden

**Comment by joshuarossi** [comment]
<img width="476" alt="screen shot 2015-10-19 at 6 19 03 pm" src="https://cloud.githubusercontent.com/assets/3466175/10593981/ecc529c0-768d-11e5-83a7-88d344909ab6.png">

**Comment by slacknation** [comment]
yah, your screenshot was where I inferred what the last field represents. anyway, in the table there are only 9 fields, but the websocket message returns 10, we should account the last field in the table.

**Comment by slacknation** [comment]
![ss](https://cloud.githubusercontent.com/assets/2529228/10603083/b537b416-774e-11e5-8467-294b4c628c42.png)
```
[
  0,
  "on",
  [
    460334357,
    "BTCUSD",
    -10.2,
    -10.2,
    "LIMIT",
    "ACTIVE",
    268.7,
    0,
    "2015-10-10T21:20:04+13:00",
    0
  ]
]
```

**Comment by joshuarossi** [comment]
yes, I edited it, so it includes the hidden order field
